#!/bin/bash
# usage: [LORES=y] ./bemuse-fran [<num> [args...]]
# args are passed to bemuse, num is 0 if not set (which bemuses all tracks)
# pass --keep to avoid overriding existing files
# to upload a specific track to Sheethost and YouTube, run
# ./bemuse-fran <num> --sheethost-username=<username> --sheethost-password=<password> --youtube-secret=<secret>

if [ $# -gt 0 ] && [ $1 != 0 ]; then ONLY_NUM=$1; fi
shift
if [[ -z $LORES ]]; then
    ARGS=$@
else
    ARGS="--width=960 --height=540 --framerate=30 $@"
fi

cp fran-bow.ini fran-bow.ini.bak
trap "rm -f fran-bow.ini.bak" EXIT

make_filter() {
    SCALE_X=$(echo $1 | sed "s#.*scale=\([0-9]*\)x.*#\1#")
    SCALE_Y=$(echo $1 | sed "s#.*x\([0-9]*\).*#\1#")
    if [[ -z $LORES ]]; then
        echo $1
    else
        echo $1 | sed "s#scale=\([0-9]*\)x#scale=$(echo "$SCALE_X / 2" \
            | bc)x#" | sed "s#x\([0-9]*\)#x$(echo "$SCALE_Y / 2" | bc)#g" \
            | sed -r "s#(.*):(.*):(.*):(.*),scale#\1/2:\2/2:\3/2:\4/2,scale#g"
    fi
}

bemuse_track() {
    NUM=$1
    SCORE=$(ls input/$NUM*.mscz | head -n1)
    if [[ $2 = left ]]; then
        POS=0
    elif [[ $2 = right ]]; then
        POS=1250
    else
        POS=$2
    fi
    shift
    shift
    if [[ -z $ONLY_NUM ]] || [[ $ONLY_NUM = $NUM ]]; then
        echo "Bemusing $SCORE ..."
        TITLE=$(basename "$SCORE" .mscz | sed "s/^[0-9. ]*//")
        if [[ ! -z $DESCRIPTION ]]; then DESCRIPTION="$DESCRIPTION\n\n"; fi
        if [[ ! -z $PUBLISH_AT ]]; then PUBLISH_AT=" --publish-at=$PUBLISH_AT"; fi
        NUM="$NUM" TITLE="$TITLE" bemuse \
                --directory=output \
                --state=fran-bow.ini \
                --filter=$DEFAULT_FILTER \
                --overlay=W/2-w/2:0 \
                --chroma="chroma/$NUM.mp4" \
                --thumbnail-convert="( fran-bow.png -scale 140% -repage +$POS-40 ) -flatten" \
                --sheethost-metadata=fran-bow.meta \
                --youtube-options='--title="Fran Bow - '"$TITLE"' (Piano Sheet Music)" --description="↓ Download links (PDF & MIDI) in the description ↓\n\nSong: '"$TITLE"'\nSource: Fran Bow\nComposer: Isak Martinsson\n\n'"$DESCRIPTION"'*** PDF and MIDI download ***\nhttp://dl.elias-kuiter.de/piano/fran-bow.html" --category=Music --tags="Fran Bow, Piano, Sheet Music, Isak Martinsson, Synthesia" --playlist=Arrangements'"$PUBLISH_AT" \
                $@ $ARGS "$SCORE"
    else
        echo "Skipping $SCORE."
    fi
}

with_state() {
    sed -i "$1s/.*/$2/" fran-bow.ini
    shift
    shift
    "$@"
    cp fran-bow.ini.bak fran-bow.ini
}

DEFAULT_SCALE=1580x864
DEFAULT_FILTER=$(make_filter crop=1480:810:220:110,scale=$DEFAULT_SCALE)
CUTSCENE_FILTER=$(make_filter crop=1510:840:205:80,scale=$DEFAULT_SCALE)
ITHERSTA_FILTER=$(make_filter crop=1460:790:210:100,scale=$DEFAULT_SCALE)

# The Bow Family
PUBLISH_AT="2020-05-19T15:00:00.00+02:00" \
DESCRIPTION="Thanks for tuning in! Many of you have subscribed and wished for more Fran Bow content over the last years.\nI still love the game and its soundtrack, and in these times, we must focus on what truly matters ... which is making piano arrangements, of course :D\n\nSo I'm happy to tell you that I've decided to create piano collections for the entire soundtrack, including updated versions of my old arrangements.\nFor now, I'll upload two videos per week (on Tuesday and Friday) so I have some time to prepare the arrangements as we go.\n\nI also thought it would be nice to experience the songs as they appear in-game, so we can follow along with Fran's journey.\n(So that's why I'm starting with track 42 on the soundtrack, in case you wondered - it's not in the game, but in the trailer.)\n\nThanks for watching - I hope you'll stick around for my new videos! :)" \
bemuse_track 42 right \
    --video-offset=-0.5

# Sitting In Company
PUBLISH_AT="2020-05-22T15:00:00.00+02:00" \
DESCRIPTION="Everything's fine ... It feels like heaven." \
bemuse_track 17 right \
    --video-offset=1 \
    --filter=$CUTSCENE_FILTER

# Inside The Children's Head
PUBLISH_AT="2020-05-26T15:00:00.00+02:00" \
DESCRIPTION="Fran has a therapy session with Dr. Deern." \
bemuse_track 12 right

# Black Tears
PUBLISH_AT="2020-05-29T15:00:00.00+02:00" \
DESCRIPTION="I will hunt you down, catch you, and bring you back to insanity." \
bemuse_track 06 right \
    --filter=$CUTSCENE_FILTER \
    --thumbnail-from=10

# Details Omitted
PUBLISH_AT="2020-06-02T15:00:00.00+02:00" \
DESCRIPTION="Fran explores the institution." \
bemuse_track 09 right

# Philmore Paranoid
PUBLISH_AT="2020-06-05T15:00:00.00+02:00" \
DESCRIPTION="A forgotten girl with no family or cat will die when the moon arrives." \
bemuse_track 23 right \
    --video-offset=0.6

# Finding The Truth
PUBLISH_AT="2020-06-09T15:00:00.00+02:00" \
DESCRIPTION="Who could have killed Fran's parents?" \
bemuse_track 02 right

# My Friend Is Leaving
PUBLISH_AT="2020-06-12T15:00:00.00+02:00" \
DESCRIPTION="Oh my dear kitty... We'll soon be together again, I promise!" \
bemuse_track 28 right

# I Can See
PUBLISH_AT="2020-06-16T15:00:00.00+02:00" \
DESCRIPTION="You clever little girl... Do you think you can just leave?" \
bemuse_track 10 right

# Sneaky Fran
bemuse_track 41 - --skip-video
PUBLISH_AT="2020-06-19T15:00:00.00+02:00" \
DESCRIPTION="At the end of the maze, Fran..." \
bemuse_track 41b left

# They Will Find You
PUBLISH_AT="2020-06-23T15:00:00.00+02:00" \
DESCRIPTION="A cat full of nuts and bolts will always be your guide." \
bemuse_track 36 right \
    --video-offset=2 \
    --filter=$CUTSCENE_FILTER

# Lost On The Path
PUBLISH_AT="2020-06-26T15:00:00.00+02:00" \
DESCRIPTION="Oh... What is this place...?" \
bemuse_track 13 right

# This Is The Forest
PUBLISH_AT="2020-06-30T15:00:00.00+02:00" \
DESCRIPTION="Hello? Is somebody home?" \
bemuse_track 16 right

# Downstairs
PUBLISH_AT="2020-07-03T15:00:00.00+02:00" \
DESCRIPTION="What a curious little door..." \
bemuse_track 11 right \
    --video-offset=2 \
    --filter=$CUTSCENE_FILTER

# Cold Walls
PUBLISH_AT="2020-07-07T15:00:00.00+02:00" \
DESCRIPTION="Welcome home, beautiful kitten!" \
bemuse_track 08 right

# Mr. Midnight
PUBLISH_AT="2020-07-10T15:00:00.00+02:00" \
DESCRIPTION="My beloved friend! I found you!" \
bemuse_track 03 right

# Duality
PUBLISH_AT="2020-07-14T15:00:00.00+02:00" \
DESCRIPTION="There you are! We were waiting for you!" \
bemuse_track 15 right

# A Little Talk
PUBLISH_AT="2020-07-17T15:00:00.00+02:00" \
DESCRIPTION="If you don't do what we ask for... Bad things will happen to your cat." \
bemuse_track 05 right \
    --thumbnail-from=30

# Fluffy Toad Bun
PUBLISH_AT="2020-07-21T15:00:00.00+02:00" \
DESCRIPTION="Here we go! Hold on tight." \
bemuse_track 39 right \
	--filter=$(make_filter crop=1480:810:220:110,scale=$DEFAULT_SCALE,setpts=1.2*PTS)

# It Hunts Me
PUBLISH_AT="2020-07-24T15:00:00.00+02:00" \
DESCRIPTION="Fraaaan! No!" \
bemuse_track 07 right \
    --video-offset=0.9 \
    --filter=$(make_filter crop=1920:864:0:100,scale=1920x864) \
    --thumbnail-from=66

# The White Rabbit
bemuse_track 04 right \
    --filter=$ITHERSTA_FILTER

# Between Black And White
bemuse_track 43 - --skip-video
bemuse_track 43b right \
    --video-offset=1 \
    --filter=$(make_filter crop=1301:665:299:100,scale=1690x864,setpts=0.61*PTS) \
    --colorkey=0x000000:0.35:0.35 \
    --thumbnail-from=7

# Get Rid Of The Dirt
bemuse_track 20 left

# Bedtime Story
bemuse_track 01 right \
    --video-offset=1.5 \
    --filter=$CUTSCENE_FILTER \
    --thumbnail-from=30

# When Things Are Said
bemuse_track 25 100